# Generated by Django 3.2 on 2021-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamm_kafka', '0003_auto_20170427_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kafkaoffset',
            options={'ordering': ('topic', 'partition', 'offset'), 'verbose_name': 'Kafka Offset', 'verbose_name_plural': 'Kafka Offsets'},
        ),
        migrations.AlterField(
            model_name='kafkaoffset',
            name='offset',
            field=models.PositiveIntegerField(default=0, help_text='The current offset in the Kafka partition', verbose_name='Kafka Offset'),
        ),
        migrations.AlterField(
            model_name='kafkaoffset',
            name='partition',
            field=models.PositiveIntegerField(help_text='The Kafka partition identifier', verbose_name='Kafka Partition ID'),
        ),
        migrations.AlterField(
            model_name='kafkaoffset',
            name='topic',
            field=models.CharField(help_text='The Kafka topic name', max_length=200, verbose_name='Kafka Topic Name'),
        ),
    ]
