# Generated by Django 3.1.5 on 2021-06-13 16:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0013_auto_20200413_1953'),
        ('users', '0009_delete_partneruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
