# Generated by Django 2.2 on 2019-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('digest', models.IntegerField(default=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_base', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
    ]
