# Generated by Django 3.1.5 on 2021-06-06 22:05

from django.db import migrations


def create_currencies(apps, schema_editor):
    Currency = apps.get_model('currency', 'Currency')
    Currency.objects.create(
        iso='RUB', symbol='₽', name='Russian ruble',
        digest=2, is_default=False, is_base=False, is_enabled=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20200413_1440'),
    ]

    operations = [
        migrations.RunPython(create_currencies),
    ]
