# Generated by Django 3.1.5 on 2021-03-24 13:32

from django.db import migrations


def create_request_statuses(apps, schema_editor):
    QuestionMessageStatus = apps.get_model('questions', 'QuestionMessageStatus')
    QuestionMessageStatus.objects.create(name='NEW')
    QuestionMessageStatus.objects.create(name='VIEWED')
    QuestionMessageStatus.objects.create(name='HIDDEN')

    QuestionRequestStatus = apps.get_model('questions', 'QuestionRequestStatus')
    QuestionRequestStatus.objects.create(name='OPEN')
    QuestionRequestStatus.objects.create(name='PROCESSING')
    QuestionRequestStatus.objects.create(name='CLOSED')
    QuestionRequestStatus.objects.create(name='REJECTED')


def remove_request_statuses(apps, schema_editor):
    QuestionMessageStatus = apps.get_model('questions', 'QuestionMessageStatus')
    QuestionMessageStatus.objects.filter(name='NEW').delete()
    QuestionMessageStatus.objects.filter(name='VIEWED').delete()
    QuestionMessageStatus.objects.filter(name='HIDDEN').delete()

    QuestionRequestStatus = apps.get_model('questions', 'QuestionRequestStatus')
    QuestionRequestStatus.objects.filter(name='OPEN').delete()
    QuestionRequestStatus.objects.filter(name='PROCESSING').delete()
    QuestionRequestStatus.objects.filter(name='CLOSED').delete()
    QuestionRequestStatus.objects.filter(name='REJECTED').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_request_statuses, remove_request_statuses),
    ]
