# Generated by Django 2.2 on 2019-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190512_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='CITY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=64, null=True, verbose_name='COUNTRY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='promo',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
