# Generated by Django 3.1.5 on 2021-06-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210610_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerUser',
        ),
    ]
