# Generated by Django 2.2 on 2019-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('cls', models.CharField(max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.TextField(blank=True, db_column='config', default=None, verbose_name='config')),
            ],
            options={
                'db_table': 'payment_systems',
            },
        ),
    ]
