# Generated by Django 2.2 on 2019-05-14 14:53

from django.db import migrations


def create_default_payment(apps, schema_editor):
    PaymentSystem = apps.get_model('payment', 'PaymentSystem')
    PaymentSystem.objects.create(
        name='Test payment system',
        is_enabled=True,
        code='test',
        config={},
        cls='TestPayment'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_payment),
    ]
