# Generated by Django 2.2 on 2019-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190514_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
