# Generated by Django 3.1.5 on 2021-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentsystem_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
