# Generated by Django 3.1.5 on 2021-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20210607_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsystem',
            name='config',
            field=models.JSONField(blank=True, db_column='config', default=dict, null=True, verbose_name='config'),
        ),
    ]
