# Generated by Django 3.1.5 on 2021-06-14 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0013_eportalwallets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EportalWallets',
            new_name='EportalWallet',
        ),
    ]
