# Generated by Django 3.1.5 on 2021-06-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20200413_1953'),
        ('payment', '0014_auto_20210614_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bwallet', models.CharField(max_length=34)),
                ('picked_at', models.DateTimeField(default=None, null=True)),
                ('expired_at', models.DateTimeField(default=None, null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.transaction')),
            ],
            options={
                'db_table': 'payment_blockchain_wallets',
            },
        ),
    ]
