# Generated by Django 3.1.5 on 2021-06-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20200413_1953'),
        ('payment', '0016_auto_20210616_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainwallet',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainwallet',
            name='picked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainwallet',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.transaction'),
        ),
    ]
