# Generated by Django 3.1.5 on 2021-06-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20210616_1147'),
        ('payment', '0019_auto_20210622_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsystem',
            name='payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
    ]
