# Generated by Django 3.1.5 on 2021-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20210624_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='exchange_rounding',
            field=models.BooleanField(default=False),
        ),
    ]
