# Generated by Django 3.1.5 on 2021-07-27 22:02

from django.db import migrations


def create_betatransfer_payment(apps, schema_editor):
    PaymentSystem = apps.get_model('payment', 'PaymentSystem')
    Currency = apps.get_model('currency', 'Currency')
    PaymentSystem.objects.create(
        name='Betatransfer',
        is_enabled=True,
        code='betatransfer',
        config={
            "payment_method": "Card",
            "public_key": "559d2059c7be5034dd1bf3ee0fb24c98",
            "secret": "b14c220883fd519227690aea6202fb2a",
        },
        payment_currency=Currency.objects.get(iso='RUB'),
        fee=5,
        position=7,
        cls='BetatransferPayment',
        min_amount=25,
        exchange_rounding=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_blockchainwallet_is_used'),
    ]

    operations = [
        migrations.RunPython(create_betatransfer_payment),
    ]
