# Generated by Django 3.2.5 on 2021-12-05 17:07

from django.db import migrations


def create_rockspay_v2_payment(apps, schema_editor):
    PaymentSystem = apps.get_model('payment', 'PaymentSystem')
    Currency = apps.get_model('currency', 'Currency')
    PaymentSystem.objects.filter(code='rockspay').update(
        name='RocksPay (P2P CIS auto)',
        is_enabled=True,
        code='rockspay',
        config={
            "callback_url": "https://ca.xyz.trading/payments/rockspay/process",
            "merchant_id": "39e6ecd5-f11b-4bbb-a1e7-ac085b611c87",
            "secret_key": "NBHcPVDJxidxitCaItakuf1VF6Wwj7IA",
            "duration": 1800,
            "additional_fields": [
                {
                    "name": "card_number",
                    "type": "card_number",
                }
            ],
            "version": 1
        },
        payment_currency=Currency.objects.get(iso='RUB'),
        fee=4,
        position=3,
        min_amount=15,
        max_amount=640,
        cls='RockspayPayment'
    )
    PaymentSystem.objects.create(
        name='RocksPay 2 (P2P CIS auto)',
        is_enabled=True,
        code='rockspay_v2',
        config={
            "callback_url": "https://ca.xyz.trading/payments/rockspay/process",
            "merchant_id": "39e6ecd5-f11b-4bbb-a1e7-ac085b611c87",
            "secret_key": "NBHcPVDJxidxitCaItakuf1VF6Wwj7IA",
            "duration": 1800,
            "additional_fields": [
                {
                    "name": "card_number",
                    "type": "card_number",
                }
            ],
            "version": 2
        },
        payment_currency=Currency.objects.get(iso='RUB'),
        fee=4,
        position=4,
        min_amount=15,
        max_amount=640,
        cls='RockspayPayment'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20210727_2202'),
    ]

    operations = [
        migrations.RunPython(create_rockspay_v2_payment),
    ]
