# Generated by Django 3.2.5 on 2022-01-19 19:33

from django.db import migrations


def create_grow_payment(apps, schema_editor):
    PaymentSystem = apps.get_model('payment', 'PaymentSystem')
    Currency = apps.get_model('currency', 'Currency')
    PaymentSystem.objects.create(
        name='Grow Payment System',
        is_enabled=False,
        code='grow',
        config={
            "sandbox_enabled": True,
            "sandbox_api_url": "https://sandbox.ps.grow.mybuilder.site",
            "api_url": "",
            "merchant_id": "117",
            "return_url": "https://ca.xyz.trading",
            "response_url": "https://ca.xyz.trading/payments/grow/success",
            "server_url": "https://ca.xyz.trading/payments/grow/process",
            "cancel_url": "https://ca.xyz.trading/deposit",
            "api5_key": "jZaA26r3NsIhbgWUxhM5GEWDNZhTYPUrIWWlRrq4jJAvoaJUUEuOhjCyQUdhJKKLqOT8mE9WCAU3A7I6DSEme1eBQpEXmEO1lWQ0Vncsv0FSRDV0edEV2cCXmqGmHVKX",
        },
        payment_currency=Currency.objects.get(iso='USD'),
        fee=5,
        position=5,
        min_amount=15,
        max_amount=640,
        cls='GrowPayment'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20211205_1707'),
    ]

    operations = [
        migrations.RunPython(create_grow_payment),
    ]
