# Generated by Django 2.2 on 2020-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt4', '0002_auto_20190901_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccounts',
            name='account_id',
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='id',
            field=models.BigIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
