# Generated by Django 2.2 on 2020-03-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20190512_2021'),
        ('mt4', '0003_auto_20200307_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='currency.Currency'),
            preserve_default=False,
        ),
    ]
