# Generated by Django 3.0.4 on 2020-04-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt4', '0004_useraccounts_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'managed': False, 'verbose_name_plural': 'mt4 accounts'},
        ),
        migrations.AlterModelOptions(
            name='trades',
            options={'managed': False, 'verbose_name_plural': 'mt4 trades'},
        ),
        migrations.AlterModelOptions(
            name='useraccounts',
            options={'verbose_name_plural': 'user accounts'},
        ),
    ]
