# Generated by Django 2.2 on 2019-05-13 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance'),
        ),
    ]
