# Generated by Django 2.2 on 2019-05-15 13:03

from django.db import migrations


def create_transaction_statuses(apps, schema_editor):
    TransactionStatus = apps.get_model('wallet', 'TransactionStatus')
    TransactionStatus.objects.create(
        name='done'
    )
    TransactionStatus.objects.create(
        name='process'
    )
    TransactionStatus.objects.create(
        name='fail'
    )
    TransactionStatus.objects.create(
        name='expire'
    )
    TransactionStatus.objects.create(
        name='error'
    )
    TransactionStatus.objects.create(
        name='decline'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190513_1016'),
    ]

    operations = [
        migrations.RunPython(create_transaction_statuses),
    ]
