# Generated by Django 2.2 on 2019-05-16 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20190515_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='running_balance',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
