# Generated by Django 2.2 on 2019-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20190516_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='params',
            field=models.TextField(blank=True, db_column='params', default=None, verbose_name='params'),
        ),
    ]
