# Generated by Django 2.2 on 2020-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20190519_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='from_wallet',
            new_name='from_to_wallet',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
