# Generated by Django 3.2.5 on 2021-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20200413_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='params',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_to_wallet',
            field=models.CharField(blank=True, default=None, max_length=32),
        ),
    ]
