# Generated by Django 3.2.5 on 2022-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20210803_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_to_wallet',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
    ]
