# Generated by Django 3.0.4 on 2020-04-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import verification.models
import verification.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('is_verificated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'card_type',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'request_status',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'request_type',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_file_name', models.CharField(max_length=128)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=verification.models.user_directory_path, validators=[verification.validators.validate_file])),
                ('comment', models.CharField(blank=True, default='', max_length=256)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.Card')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='verification.RequestStatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='verification.RequestType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_requests',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='declaration_set', to='verification.VerificationRequest')),
                ('identification', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='identification_set', to='verification.VerificationRequest')),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_set', to='verification.VerificationRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='verification.CardsType'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
