# Generated by Django 3.0.4 on 2020-03-31 16:24

from django.db import migrations


def create_account_types(apps, schema_editor):
    RequestType = apps.get_model('verification', 'RequestType')
    RequestType.objects.create(
        enabled=True,
        required=True,
        name='CARD_FRONT',
        description='',
    )
    RequestType.objects.create(
        enabled=True,
        required=True,
        name='CARD_BACK',
        description='',
    )
    RequestType.objects.create(
        enabled=True,
        required=True,
        name='DD',
        description='',
    )
    RequestType.objects.create(
        enabled=True,
        required=True,
        name='ID',
        description='',
    )
    RequestType.objects.create(
        enabled=True,
        required=True,
        name='INVOICE',
        description='',
    )
    RequestType.objects.create(
        enabled=False,
        required=False,
        name='OTHER',
        description='',
    )

    RequestStatus = apps.get_model('verification', 'RequestStatus')
    RequestStatus.objects.create(
        name='APPROVED',
    )
    RequestStatus.objects.create(
        name='PENDING',
    )
    RequestStatus.objects.create(
        name='DECLINED',
    )
    RequestStatus.objects.create(
        name='EXPIRED',
    )


def remove_account_types(apps, schema_editor):
    RequestType = apps.get_model('verification', 'RequestType')
    RequestType.objects.filter(name='CARD_FRONT').delete()
    RequestType.objects.filter(name='CARD_BACK').delete()
    RequestType.objects.filter(name='DD').delete()
    RequestType.objects.filter(name='ID').delete()
    RequestType.objects.filter(name='INVOICE').delete()
    RequestType.objects.filter(name='OTHER').delete()

    RequestStatus = apps.get_model('verification', 'RequestStatus')
    RequestStatus.objects.filter(name='APPROVED').delete()
    RequestStatus.objects.filter(name='PENDING').delete()
    RequestStatus.objects.filter(name='DECLINED').delete()
    RequestStatus.objects.filter(name='EXPIRED').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_account_types, remove_account_types),
    ]
