# Generated by Django 3.0.4 on 2020-04-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20200406_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verification.Card'),
        ),
    ]
