# Generated by Django 3.0.4 on 2020-04-10 11:22
from django.db import migrations


def create_card_types(apps, schema_editor):
    CardsType = apps.get_model('verification', 'CardsType')
    CardsType.objects.create(
        name='NORMAL',
        description='Normal Visa/MasterCard',
    )
    CardsType.objects.create(
        name='VIRTUAL',
        description='Some virtual card'
    )


def remove_card_types(apps, schema_editor):
    CardsType = apps.get_model('verification', 'CardsType')
    CardsType.objects.filter(name='NORMAL').delete()
    CardsType.objects.filter(name='VIRTUAL').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_auto_20200406_2034'),
    ]

    operations = [
        migrations.RunPython(create_card_types, remove_card_types),
    ]
