# Generated by Django 3.0.4 on 2020-04-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_auto_20200410_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verification.Card'),
        ),
    ]
