# Generated by Django 3.1.5 on 2021-05-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_auto_20200413_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='is_verificated',
            new_name='is_verified',
        ),
    ]
